services:
  postgres:
    container_name: ariesview51-postgres
    image: postgres:15-alpine
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ariesview
      POSTGRES_PASSWORD: Ariesview123
      POSTGRES_DB: ariesview
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ariesview"]
      interval: 5s
      timeout: 5s
      retries: 5

# Removed the persistent volume definition as requested 