version: '3.8'

services:
  postgres:
    container_name: ariesview51-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ariesview
      POSTGRES_PASSWORD: Ariesview123
      POSTGRES_DB: ariesview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ariesview"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 