/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'navy': {
          700: '#1e3a5f',
          900: '#0a1929',
        },
        'blue': {
          500: '#3b82f6',
          300: '#93c5fd',
        },
        'gray': {
          100: '#f3f4f6',
          200: '#e5e7eb',
          400: '#9ca3af',
          800: '#1f2937',
          900: '#111827',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1.5' }],
        'sm': ['0.875rem', { lineHeight: '1.5715' }],
        'base': ['1rem', { lineHeight: '1.5', letterSpacing: '-0.017em' }],
        'lg': ['1.125rem', { lineHeight: '1.5', letterSpacing: '-0.017em' }],
        'xl': ['1.25rem', { lineHeight: '1.5', letterSpacing: '-0.017em' }],
        '2xl': ['1.5rem', { lineHeight: '1.415', letterSpacing: '-0.037em' }],
        '3xl': ['1.875rem', { lineHeight: '1.3333', letterSpacing: '-0.037em' }],
        '4xl': ['2.25rem', { lineHeight: '1.2777', letterSpacing: '-0.037em' }],
        '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.037em' }],
        '6xl': ['4rem', { lineHeight: '1', letterSpacing: '-0.037em' }],
        '7xl': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.037em' }],
      },
      animation: {
        'code-1': 'code-1 4s infinite',
        'code-2': 'code-2 4s infinite',
        'code-3': 'code-3 4s infinite',
        'code-4': 'code-4 4s infinite',
        'code-5': 'code-5 4s infinite',
        'code-6': 'code-6 4s infinite',
        'breath': 'breath 4s infinite',
        'float': 'float 4s infinite',
        'line': 'line 4s infinite',
        'infinite-scroll': 'infinite-scroll 25s linear infinite',
      },
      boxShadow: {
        'xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      },
      borderRadius: {
        'xs': '0.125rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
  ],
  safelist: [
    'text-sm',
    'font-medium',
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-lg',
    'whitespace-nowrap',
    'transition-all',
    'px-4',
    'py-[11px]',
    'shadow-lg',
    'px-3',
    'py-[5px]',
    'shadow-sm',
    'border',
    'border-gray-200',
    'shadow-xs',
    'focus:ring-0',
    'focus:ring-offset-0',
    'bg-white',
    'py-2.5',
    'px-4',
    'focus:border-blue-300',
    'placeholder-gray-400',
    'pr-10',
    'text-gray-800',
    'checked:bg-blue-500',
    'checked:border-transparent',
    'focus-visible:not-checked:border-blue-300',
    'rounded-xs',
  ],
} 